Create a numpy array called "grades" that contains the following grades: [85, 90, 88, 92, 95, 80, 75, 98, 89, 83]


Instructions

Create a new file called "grades_analysis.py"
Import the numpy library and create the "grades" array as specified above.
Use numpy functions to calculate the mean, median, and standard deviation of the grades.
Use numpy function to find the maximum and minimum of the grades.
Use numpy function to sort the grades in ascending order.
Use numpy function to find the index of the highest grade in the array.
Use numpy function to count the number of students who scored above 90.
Use numpy function to calculate the percentage of students who scored above 90.
Use numpy function to calculate the percentage of students who scored below 75.
Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers".
Create a new array called "passing_grades" that contains all the grades above 75.
Print the result of all the above steps.
Note:

to calculate percentage use numpy.mean(grades > 90) * 100
to extract the grades above 90 use grades[grades > 90]
to extract the grades above 75 use grades[grades > 75]
You can use other numpy functions as well to analyze the data as you want. The above steps are just examples of what can be done.


f what can be done.




In [1]:
# Import the numpy library and create the "grades" array as specified above.
import numpy as np

In [3]:
grades = np.array ([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])
grades

array([85, 90, 88, 92, 95, 80, 75, 98, 89, 83])

In [5]:
# Use numpy functions to calculate the mean, median, and standard deviation of the grades.
# mean
mean_grades = np.mean(grades)
mean_grades

87.5

In [6]:
# Median
median_grades = np.median(grades)
median_grades

88.5

In [28]:
# Standard Deviation
std_grades = np.std(grades)
std_grades

6.591661399070799

In [8]:
# Use numpy function to find the maximum and minimum of the grades.
# Maximum
max_grades = np.max(grades)
max_grades

98

In [9]:
# Minimum
min_grades = np.min(grades)
min_grades

75

In [12]:
# Use numpy function to sort the grades in ascending order.
# Sort
sort_grades = np.sort(grades)
sort_grades

array([75, 80, 83, 85, 88, 89, 90, 92, 95, 98])

In [13]:
# Use numpy function to find the index of the highest grade in the array.
index_highest_grade = np.argmax(grades)
index_highest_grade

7

In [20]:
# Use numpy function to count the number of students who scored above 90.
count_above_90 = np.sum(grades >90)
count_above_90

3

In [21]:
# Use numpy function to calculate the percentage of students who scored above 90.
percentage_above_90 = np.mean(grades >90) * 100
percentage_above_90

30.0

In [22]:
# Use numpy function to calculate the percentage of students who scored below 75.
percentage_below_75 = np.mean(grades < 75) * 100
percentage_below_75

0.0

In [24]:
# Use numpy function to extract all the grades above 90 and put them in a new array called "high_performers".
high_performers = grades [grades >90]
high_performers

array([92, 95, 98])

In [26]:
# Create a new array called "passing_grades" that contains all the grades above 75.
passing_grades = grades[grades > 75]
passing_grades

array([85, 90, 88, 92, 95, 80, 98, 89, 83])

In [30]:
# Print the result of all the above steps.
print(f"Grades: {grades}")
print(f"Mean of Grades: {mean_grades}")
print(f"Median of Grades: {median_grades}")
print(f"Standard Deviation of Grades: {std_grades}")
print(f"Maximum of Grades: {max_grades}")
print(f"Minimum of Grades: {min_grades}")
print(f"Sorted Grades: {sort_grades}")
print(f"Index of highest grade: {index_highest_grade}")
print(f"Number of score above 90: {count_above_90}")
print(f"Percentage of score above 90: {percentage_above_90}%")
print(f"Percentage of score below 75: {percentage_below_75}%")
print(f"High Performers: {high_performers}")
print(f"Passing Grades: {passing_grades}")

Grades: [85 90 88 92 95 80 75 98 89 83]
Mean of Grades: 87.5
Median of Grades: 88.5
Standard Deviation of Grades: 6.591661399070799
Maximum of Grades: 98
Minimum of Grades: 75
Sorted Grades: [75 80 83 85 88 89 90 92 95 98]
Index of highest grade: 7
Number of score above 90: 3
Percentage of score above 90: 30.0%
Percentage of score below 75: 0.0%
High Performers: [92 95 98]
Passing Grades: [85 90 88 92 95 80 98 89 83]
